version: '3.8'

services:
  postgres:
    image: "postgres"
    container_name: "postgres-event-sourcing-cqrs-rbdms-sample"
    hostname: "postgres-002"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: "/data/postgres"
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: "postgres-002"
        target: "/data/postgres"
      - $PWD/V1.0__eventstore_db.sql:/docker-entrypoint-initdb.d/1-schema.sql
    networks:
      - "network-event-sourcing-cqrs-rbdms-sample.local"
    restart: unless-stopped
#---------------------------------------------------------------------------------------------------------------------
networks:
  network-event-sourcing-cqrs-rbdms-sample.local:
    name: "network-event-sourcing-cqrs-rbdms-sample.local"
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 171.28.0.0/16
#---------------------------------------------------------------------------------------------------------------------
volumes:
  postgres-002:
    name: "postgres-002"
