CREATE TABLE STREAM (
  ID UUID PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  CONSTRAINT STREAM_UNIQUE UNIQUE  (ID, NAME)
);

CREATE TABLE AGGREGATE (
  ID UUID PRIMARY KEY,
  STREAM_ID UUID NOT NULL REFERENCES STREAM(ID),
  NAME VARCHAR(255) NOT NULL,
  VERSION INT4 NOT NULL,
  CONSTRAINT AGGREGATE_UNIQUE UNIQUE  (ID, NAME, VERSION, STREAM_ID)
);

CREATE TABLE BOOKING_STREAM (
  ID UUID PRIMARY KEY,
  STREAM_ID UUID NOT NULL REFERENCES STREAM(ID),
  AGGREGATE_ID UUID NOT NULL REFERENCES AGGREGATE(ID),
  VERSION INT4 NOT NULL,
  EVENT_TYPE VARCHAR(255) NOT NULL,
  JSON_DATA JSON NOT NULL,
  STREAM_OFFSET INT4 AUTO_INCREMENT NOT NULL,
  CONSTRAINT STREAM_BOOKING_EVENT_UNIQUE UNIQUE (AGGREGATE_ID, VERSION)
);

CREATE TABLE SUBSCRIPTION (
  ID UUID PRIMARY KEY,
  STREAM_ID UUID NOT NULL REFERENCES STREAM(ID),
  NAME VARCHAR(255) UNIQUE,
  STREAM_OFFSET INT4 NOT NULL,
  CONSTRAINT SUBSCRIPTION_UNIQUE UNIQUE (NAME, STREAM_ID)
);

CREATE TABLE BOOKING (
  ID UUID PRIMARY KEY,
  VERSION INT4 NOT NULL,
  STATUS VARCHAR(255)
);
