CREATE TABLE AGGREGATE (
  ID UUID PRIMARY KEY,
  NAME VARCHAR NOT NULL,
  VERSION INT4 NOT NULL,
  CONSTRAINT AGGREGATE_UNIQUE UNIQUE  (ID, NAME, VERSION)
);

CREATE TABLE SUBSCRIPTION (
  ID UUID PRIMARY KEY,
  NAME VARCHAR UNIQUE,
  AGGREGATE_NAME VARCHAR NOT NULL,
  OFFSET_EVENT INT4 NOT NULL,
  CONSTRAINT SUBSCRIPTION_UNIQUE UNIQUE (NAME, AGGREGATE_NAME)
);

CREATE TABLE BANK_ACCOUNT_EVENT(
  ID UUID PRIMARY KEY,
  AGGREGATE_ID UUID NOT NULL REFERENCES AGGREGATE(ID),
  SOURCE VARCHAR ,
  SPEC_VERSION VARCHAR,
  TYPE VARCHAR NOT NULL,
  DATA_CONTENT_TYPE VARCHAR,
  SUBJECT VARCHAR,
  DATA JSON NOT NULL,
  DATA_BASE64 VARCHAR,
  DATA_SCHEMA VARCHAR,
  VERSION INT4 NOT NULL,
  OFFSET_DATE_TIME TIMESTAMP,
  OFFSET_EVENT INT4 AUTO_INCREMENT NOT NULL,
  CONSTRAINT BANK_ACCOUNT_EVENT_UNIQUE UNIQUE (AGGREGATE_ID, VERSION)
);

CREATE TABLE BANK_ACCOUNT (
  ID UUID PRIMARY KEY,
  VERSION INT4 NOT NULL,
  STATUS VARCHAR
);
